### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [StevenLooman/python-didl-lite#12]
Could you please tag the source again? Otherwise all distributions which were shipping this Python module  and were using the GitHub releases need to change their description to build the packages.

Thanks

**Comment by StevenLooman** [comment]
Done: https://github.com/StevenLooman/python-didl-lite/releases/tag/1.4.0

Thank you for reporting this @fabaff! I forgot to push the tag, sorry for the hassle.
